// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZ__pDbcSRddQMUT_VeU_03qx70JhPqlw',
    appId: '1:242543034495:web:abd6890b8fa25108c53f4a',
    messagingSenderId: '242543034495',
    projectId: 'helponmaps',
    authDomain: 'helponmaps.firebaseapp.com',
    storageBucket: 'helponmaps.firebasestorage.app',
    measurementId: 'G-PZB2WTKF3B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwkH7tg561Ux3yMplGZUG6nMKTy6D8HN8',
    appId: '1:242543034495:android:a6edaa953ec31d9bc53f4a',
    messagingSenderId: '242543034495',
    projectId: 'helponmaps',
    storageBucket: 'helponmaps.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8d_9v3Eq3TPeXbo59SF7XspFmj6pmIFs',
    appId: '1:242543034495:ios:8c05305546815993c53f4a',
    messagingSenderId: '242543034495',
    projectId: 'helponmaps',
    storageBucket: 'helponmaps.firebasestorage.app',
    iosBundleId: 'com.example.helpOnMaps',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8d_9v3Eq3TPeXbo59SF7XspFmj6pmIFs',
    appId: '1:242543034495:ios:8c05305546815993c53f4a',
    messagingSenderId: '242543034495',
    projectId: 'helponmaps',
    storageBucket: 'helponmaps.firebasestorage.app',
    iosBundleId: 'com.example.helpOnMaps',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZ__pDbcSRddQMUT_VeU_03qx70JhPqlw',
    appId: '1:242543034495:web:d5f89e5e91fcd669c53f4a',
    messagingSenderId: '242543034495',
    projectId: 'helponmaps',
    authDomain: 'helponmaps.firebaseapp.com',
    storageBucket: 'helponmaps.firebasestorage.app',
    measurementId: 'G-1BRCN1MPLT',
  );

}